-- Add batch + ETL columns to pipeline_jobs table
ALTER TABLE pipeline_jobs
ADD COLUMN IF NOT EXISTS app_generation BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS batch_id TEXT,
ADD COLUMN IF NOT EXISTS batch_order INTEGER,
ADD COLUMN IF NOT EXISTS batch_total INTEGER,
ADD COLUMN IF NOT EXISTS etl_status TEXT,
ADD COLUMN IF NOT EXISTS etl_target_db_url TEXT,
ADD COLUMN IF NOT EXISTS etl_error TEXT,
ADD COLUMN IF NOT EXISTS etl_result JSONB,
ADD COLUMN IF NOT EXISTS etl_started_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS etl_completed_at TIMESTAMP;
